version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - gosec
  settings:
    misspell:
      ignore-words:
        - mosquitto
    gosec:
      excludes:
        - G402
        - G114
